import type { Metadata } from "next";
import "./styles/globals.css";
import { MAIN_FONT } from "./constants/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={MAIN_FONT.className}>{children}</body>
    </html>
  );
}
